// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreSample.Models.DTO;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NetCoreSample.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210131172817_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NetCoreSample.Models.DTO.JobTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("JobTask");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fdf8eb6-0613-44dd-853b-a244a880409d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 1, 31, 17, 28, 17, 486, DateTimeKind.Unspecified).AddTicks(4649), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ff40f52d-741c-4c6c-acc8-a423b9447678"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 1, 31, 17, 28, 17, 486, DateTimeKind.Unspecified).AddTicks(5628), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("b41d22f7-0f5e-41e1-88f0-afae48cd1d16"),
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 1, 31, 17, 28, 17, 486, DateTimeKind.Unspecified).AddTicks(5650), new TimeSpan(0, 0, 0, 0, 0)),
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
